# SPDX-FileCopyrightText: © 2026 TEC <contact@tecosaur.net>
# SPDX-License-Identifier: MPL-2.0

# Tests for PackedParselets in isolation — no AbstractIdentifier, no FastIdentifiers API.

using Test

# Load PackedParselets through FastIdentifiers (it's an inner module)
using FastIdentifiers.DefId.PackedParselets

const PP = PackedParselets

# --- Test harness ---

# Abstract base type for test types (not AbstractIdentifier)
abstract type AbstractPacked end

# Minimal finalize hook: generates parse/tryparse using ArgumentError.
# tobytes, print, and string are already generated by assemble_type.
function test_finalize!(block::Expr, exprs::PP.PatternExprs,
                        state::PP.ParserState, name::Symbol)
    M = state.method_module
    ename = esc(name)
    errmsgs = Tuple(state.errconsts)
    push!(block.args,
        :(function $(GlobalRef(Base, :parse))(::Type{$ename}, id::AbstractString)
              result, pos = $(GlobalRef(M, :parsebytes))($ename, codeunits(id))
              if result isa $ename
                  pos > ncodeunits(id) || throw(ArgumentError("Unparsed trailing content in " * repr(id)))
                  result
              else
                  throw(ArgumentError(@inbounds $errmsgs[result]))
              end
          end))
    push!(block.args,
        :(function $(GlobalRef(Base, :tryparse))(::Type{$ename}, id::AbstractString)
              result, pos = $(GlobalRef(M, :parsebytes))($ename, codeunits(id))
              result isa $ename && pos > ncodeunits(id) ? result : nothing
          end))
end

# Convenience: define a packed type using CORE_SEGMENTS targeting this test module.
# Strip Expr(:escape, x) wrappers inserted by esc() — needed when
# eval'ing generated code directly instead of macro-expanding it.
function strip_esc(expr::Expr)
    if Meta.isexpr(expr, :escape, 1)
        return strip_esc(expr.args[1])
    end
    Expr(expr.head, map(strip_esc, expr.args)...)
end
strip_esc(x) = x

function _packed_assemble(mod::Module, name::Symbol, pattern;
                          casefold::Bool = true,
                          segments::NamedTuple = PP.CORE_SEGMENTS,
                          global_kwargs::Tuple = (),
                          finalize_fn::Function = test_finalize!)
    root = PP.ParseBranch(1, nothing, :root, 0, 0, 0, 0, 0, 0)
    state = PP.ParserState(name, mod, 0, AbstractPacked, PP,
                           (;), PP.ParseBranch[root], String[],
                           Pair{Symbol, PP.SegmentOutput}[])
    nctx = PP.NodeCtx(:current_branch, root)
    nctx = PP.NodeCtx(nctx, :casefold, casefold)
    exprs = PP.PatternExprs(([], [], [], []))
    PP.pattern_dispatch!(exprs, state, nctx, segments, global_kwargs, pattern)
    PP.assemble_type(exprs, state, name, segments; finalize_fn)
end

# For eval: strips esc wrappers that are only meaningful in macro context.
function packed_deftype(mod::Module, name::Symbol, pattern; kwargs...)
    strip_esc(_packed_assemble(mod, name, pattern; kwargs...))
end

# For macro expansion: esc wrappers are needed for hygiene.
macro defpacked(name, pattern)
    _packed_assemble(__module__, name, pattern)
end

# --- Core segment tests ---

@testset "PackedParselets" begin

@testset "literal + digits" begin
    @defpacked LitDigit ("AB", :val(digits(4, pad=4)))
    @test parse(LitDigit, "AB0042") isa LitDigit
    x = parse(LitDigit, "AB0042")
    @test x.val == 42
    @test string(x) == "AB0042"
    @test tryparse(LitDigit, "AB0042") == x
    @test tryparse(LitDigit, "XX0042") === nothing
    @test tryparse(LitDigit, "AB") === nothing
    # Round-trip
    for v in (0, 1, 9999)
        @test parse(LitDigit, string(LitDigit(v))) == LitDigit(v)
    end
    # Type properties
    @test LitDigit <: AbstractPacked
    @test isprimitivetype(LitDigit)
    @test PP.parsebounds(LitDigit) == (6, 6)
    @test PP.printbounds(LitDigit) == (6, 6)
end

@testset "choice" begin
    @defpacked Colour (choice("red", "green", "blue"))
    @test parse(Colour, "red") isa Colour
    @test parse(Colour, "green") isa Colour
    @test parse(Colour, "blue") isa Colour
    @test tryparse(Colour, "yellow") === nothing
    for c in ("red", "green", "blue")
        @test string(parse(Colour, c)) == c
    end
end

@testset "choice with field" begin
    @defpacked Flagged (:kind(choice("alpha", "beta", "gamma")),
                        "-", :num(digits(3, pad=3)))
    x = parse(Flagged, "beta-007")
    @test x.kind == :beta
    @test x.num == 7
    @test string(x) == "beta-007"
    @test propertynames(x) == (:kind, :num)
end

@testset "skip" begin
    @defpacked Skipped (skip("http://", "https://"), :val(digits(5)))
    @test parse(Skipped, "12345").val == 12345
    @test parse(Skipped, "http://12345").val == 12345
    @test parse(Skipped, "https://12345").val == 12345
    @test string(parse(Skipped, "http://99999")) == "99999"
end

@testset "letters" begin
    @defpacked Code3 (:code(letters(3)))
    x = parse(Code3, "ABC")
    @test x.code == "ABC"
    @test string(x) == "ABC"
    # Case folding (default casefold=true)
    @test parse(Code3, "abc") == parse(Code3, "ABC")
end

@testset "alphnum" begin
    @defpacked AlphaNum4 (:tag(alphnum(4)))
    x = parse(AlphaNum4, "AB12")
    @test string(x) == "AB12"
    @test parse(AlphaNum4, "ab12") == x
end

@testset "hex" begin
    @defpacked HexId (:h(hex(4)))
    x = parse(HexId, "DEAD")
    @test string(x) == "DEAD"
    @test parse(HexId, "dead") == x
    @test tryparse(HexId, "GHIJ") === nothing
end

@testset "charset" begin
    @defpacked BinId (:bits(charset(8, '0':'1')))
    x = parse(BinId, "10110010")
    @test string(x) == "10110010"
    @test tryparse(BinId, "10110020") === nothing
end

@testset "optional" begin
    @defpacked OptSuffix (:num(digits(4, pad=4)),
                          optional(".", :ext(digits(max=255))))
    # Without optional
    x = parse(OptSuffix, "0042")
    @test x.num == 42
    @test x.ext === nothing
    @test string(x) == "0042"
    # With optional
    y = parse(OptSuffix, "0042.7")
    @test y.num == 42
    @test y.ext == 7
    @test string(y) == "0042.7"
    # Round-trip
    @test parse(OptSuffix, string(x)) == x
    @test parse(OptSuffix, string(y)) == y
end

@testset "nested optional" begin
    @defpacked NestedOpt (:a(digits(3, pad=3)),
                          optional(".", :b(digits(max=99)),
                                   optional(".", :c(digits(max=99)))))
    x = parse(NestedOpt, "042")
    @test x.a == 42 && x.b === nothing && x.c === nothing
    y = parse(NestedOpt, "042.5")
    @test y.a == 42 && y.b == 5 && y.c === nothing
    z = parse(NestedOpt, "042.5.10")
    @test z.a == 42 && z.b == 5 && z.c == 10
    for v in (x, y, z)
        @test parse(NestedOpt, string(v)) == v
    end
end

@testset "constructor" begin
    @defpacked Constructed (:a(digits(3, pad=3)), "-",
                            :b(choice("x", "y", "z")))
    x = Constructed(42, :y)
    @test x.a == 42
    @test x.b == :y
    @test string(x) == "042-y"
    @test parse(Constructed, "042-y") == x
end

@testset "optional constructor" begin
    @defpacked OptCons (:id(digits(4, pad=4)),
                        optional("v", :ver(digits(max=255))))
    x = OptCons(5, 3)
    @test x.id == 5 && x.ver == 3
    @test string(x) == "0005v3"
    y = OptCons(5, nothing)
    @test y.id == 5 && y.ver === nothing
    @test string(y) == "0005"
end

@testset "isless" begin
    @defpacked Ordered (:n(digits(4)))
    a = parse(Ordered, "0100")
    b = parse(Ordered, "0200")
    @test a < b
    @test !(b < a)
    @test !(a < a)
end

@testset "segments introspection" begin
    @defpacked SegInspect ("X", :val(digits(3, pad=3)))
    schema = PP.segments(SegInspect)
    @test length(schema) >= 1
    @test any(s -> s.label == :val, schema)
    x = parse(SegInspect, "X042")
    vals = PP.segments(x)
    @test length(vals) >= 1
end

@testset "variable-width digits" begin
    @defpacked VarDig (:n(digits(1:5)))
    for v in (0, 9, 99, 999, 9999, 99999)
        x = VarDig(v)
        @test parse(VarDig, string(x)) == x
    end
    @test tryparse(VarDig, "100000") === nothing  # exceeds 5 digits
end

@testset "show forms" begin
    @defpacked ShowTest (:id(digits(3, pad=3)))
    x = ShowTest(42)
    # Constructor form (no :limit)
    @test sprint(show, x) == "ShowTest(42)"
    # Compact form (:limit) uses print(io, id)
    @test sprint(show, x; context=IOContext(stdout, :limit => true)) == "ShowTest:042"
    # With typeinfo suppressed
    @test sprint(show, x; context=IOContext(stdout, :limit => true, :typeinfo => ShowTest)) == "042"
end

@testset "print and string" begin
    @defpacked PrintTest (:a(digits(2, pad=2)), "-", :b(letters(3)))
    x = parse(PrintTest, "42-ABC")
    @test string(x) == "42-ABC"
    @test sprint(print, x) == "42-ABC"
end

eval(packed_deftype(@__MODULE__, :EmbInner, :(:x(digits(2, pad=2)))))
eval(packed_deftype(@__MODULE__, :EmbOuter,
    :(("E", :inner(embed(EmbInner)), "-", :extra(digits(2, pad=2))))))
@testset "embed" begin
    x = parse(EmbOuter, "E05-10")
    @test x.inner isa EmbInner
    @test x.inner.x == 5
    @test x.extra == 10
    @test string(x) == "E05-10"
    @test parse(EmbOuter, string(x)) == x
end

@testset "case folding disabled" begin
    expr = packed_deftype(@__MODULE__, :CaseSensitive,
                          :((choice(casefold=false, "Abc", "DEF")));
                          casefold=false)
    eval(expr)
    @test tryparse(CaseSensitive, "Abc") isa CaseSensitive
    @test tryparse(CaseSensitive, "DEF") isa CaseSensitive
    @test tryparse(CaseSensitive, "abc") === nothing
    @test tryparse(CaseSensitive, "def") === nothing
end

# --- Extension API: custom timestamp segment ---

@testset "custom segment (timestamp)" begin
    # Define a timestamp segment that parses YYYYMMDD into a packed integer.
    # Date is packed as (year-2000)*10000 + month*100 + day (fits in 24 bits).
    function compile_timestamp(state::PP.ParserState, nctx::PP.NodeCtx,
                               ::PP.SegmentDef, args::Vector{Any})
        isempty(args) || throw(ArgumentError("timestamp takes no arguments"))
        option = get(nctx, :optional, nothing)
        claims = PP.unclaimed_sentinel(nctx)
        presbits = claims ? 1 : 0
        nbits = 24 + presbits
        fieldvar = get(nctx, :fieldvar, gensym("timestamp"))
        nbits_pos = state.bits + nbits
        # Parse: read 8 digits, pack as (Y-2000)*10000 + M*100 + D
        yvar = gensym("year"); mvar = gensym("month"); dvar = gensym("day")
        tvar = gensym("tsval")
        errmsg = PP.register_errmsg(state, "Invalid timestamp")
        opt_label = get(nctx, :opt_label, nothing)
        notfound = if isnothing(option)
            [:(return ($errmsg, pos))]
        else
            [PP.opt_fail_expr(option, opt_label)]
        end
        ylen = gensym("ylen"); mlen = gensym("mlen"); dlen = gensym("dlen")
        parse_exprs = PP.ExprVarLine[
            :(($ylen, $yvar) = PP.parseint(UInt32, idbytes, pos, 10, 4)),
            :($ylen == 4 || $(notfound...)),
            :(($mlen, $mvar) = PP.parseint(UInt32, idbytes, pos + 4, 10, 2)),
            :($mlen == 2 || $(notfound...)),
            :(($dlen, $dvar) = PP.parseint(UInt32, idbytes, pos + 6, 10, 2)),
            :($dlen == 2 || $(notfound...)),
            :($tvar = UInt32(($yvar - 2000) * 10000 + $mvar * 100 + $dvar)),
            PP.emit_pack(state, UInt32, tvar, nbits_pos - presbits)]
        if claims
            push!(parse_exprs, PP.emit_pack(state, Bool, true, nbits_pos))
        end
        push!(parse_exprs, :(pos += 8))
        # Extract
        fextract = :($fieldvar = $(PP.emit_extract(state, nbits_pos - presbits, 24)))
        # Print
        print_exprs = PP.ExprVarLine[
            :(print(io, string(div($fieldvar, 10000) + 2000, pad=4))),
            :(print(io, string(div($fieldvar % 10000, 100), pad=2))),
            :(print(io, string($fieldvar % 100, pad=2)))]
        # Constructor impart
        argvar = gensym("arg_ts")
        argconv = gensym("arg_ts_u32")
        impart_body = Any[:($argconv = $argvar % UInt32),
                          PP.emit_pack(state, UInt32, argconv, nbits_pos - presbits)]
        if presbits > 0
            push!(impart_body, PP.emit_pack(state, Bool, true, nbits_pos))
        end
        sentinel = if claims; PP.SentinelSpec((0, presbits)) else nothing end
        PP.value_segment_output(;
            nbits=nbits, fieldvar,
            desc="timestamp (YYYYMMDD)", shortform="YYYYMMDD",
            argvar, base_argtype=:Integer, option,
            sentinel, parsed=8:8, printed=8:8,
            parse=parse_exprs,
            extract_setup=PP.ExprVarLine[fextract], extract_value=fieldvar,
            impart_body, print=print_exprs)
    end

    # Finalize hook: generates a `dateof(::T) -> (year, month, day)` method.
    function finalize_timestamp!(block::Expr, exprs::PP.PatternExprs,
                                 state::PP.ParserState, name::Symbol)
        ts_output = let idx = findfirst(p -> first(p) === :timestamp, state.segment_outputs)
            isnothing(idx) ? nothing : last(state.segment_outputs[idx])
        end
        isnothing(ts_output) && return
        ename = esc(name)
        extract_exprs = copy(ts_output.codegen.extract)
        PP.implement_casting!(state, extract_exprs)
        val_expr = extract_exprs[end]
        setup = extract_exprs[1:end-1]
        push!(block.args,
            :(function dateof(id::$ename)
                  $(setup...)
                  v = $val_expr
                  (div(v, 10000) + 2000, div(v % 10000, 100), v % 100)
              end))
    end

    # Combined finalize: both test_finalize and timestamp hook
    function ts_finalize!(block::Expr, exprs::PP.PatternExprs,
                          state::PP.ParserState, name::Symbol)
        test_finalize!(block, exprs, state, name)
        finalize_timestamp!(block, exprs, state, name)
    end

    TIMESTAMP_SEGMENTS = merge(PP.CORE_SEGMENTS, PP.segment_set(
        PP.SegmentDef(:timestamp, compile_timestamp, ())))

    ts_expr = packed_deftype(@__MODULE__, :Event,
        :(("EVT-", :date(timestamp()), "-", :id(digits(3, pad=3))));
        segments=TIMESTAMP_SEGMENTS, finalize_fn=ts_finalize!)
    eval(ts_expr)

    @test Event <: AbstractPacked
    @test isprimitivetype(Event)

    @testset "parsing" begin
        x = parse(Event, "EVT-20250615-042")
        @test x isa Event
        @test x.id == 42
        @test tryparse(Event, "EVT-20250615-042") == x
        @test tryparse(Event, "EVT-BAD-042") === nothing
        @test tryparse(Event, "XYZ-20250615-042") === nothing
    end

    @testset "round-trip" begin
        x = parse(Event, "EVT-20250615-042")
        @test string(x) == "EVT-20250615-042"
        @test parse(Event, string(x)) == x
    end

    @testset "constructor" begin
        # date is packed as (2025-2000)*10000 + 6*100 + 15 = 250615
        x = Event(250615, 42)
        @test string(x) == "EVT-20250615-042"
    end

    @testset "dateof finalize hook" begin
        x = parse(Event, "EVT-20250615-042")
        @test dateof(x) == (2025, 6, 15)
        y = parse(Event, "EVT-20001231-001")
        @test dateof(y) == (2000, 12, 31)
    end

    @testset "segments" begin
        schema = PP.segments(Event)
        @test length(schema) >= 2
        ts_seg = first(s for s in schema if s.kind == :timestamp)
        @test ts_seg.desc == "timestamp (YYYYMMDD)"
    end

    @testset "optional timestamp" begin
        ts_opt_expr = packed_deftype(@__MODULE__, :MaybeEvent,
            :((:id(digits(3, pad=3)), optional("-", :date(timestamp()))));
            segments=TIMESTAMP_SEGMENTS, finalize_fn=ts_finalize!)
        eval(ts_opt_expr)
        x = parse(MaybeEvent, "042")
        @test x.id == 42
        @test x.date === nothing
        y = parse(MaybeEvent, "042-20250101")
        @test y.id == 42
        @test y.date isa Integer
        @test string(x) == "042"
        @test string(y) == "042-20250101"
        @test parse(MaybeEvent, string(x)) == x
        @test parse(MaybeEvent, string(y)) == y
    end
end

# --- default_finalize! ---

@testset "default_finalize! (no-op)" begin
    # With default_finalize!, no parse/tryparse are generated,
    # but tobytes/print/string are (generated by assemble_type).
    expr = packed_deftype(@__MODULE__, :Bare,
                          :(:val(digits(3, pad=3)));
                          finalize_fn = PP.default_finalize!)
    eval(expr)
    @test Bare <: AbstractPacked
    @test PP.parsebounds(Bare) == (3, 3)
    # parsebytes works
    result, pos = PP.parsebytes(Bare, codeunits("042"))
    @test result isa Bare
    @test pos == 4
    @test result.val == 42
    # Constructor works
    @test Bare(99).val == 99
    # string works (generated by assemble_type)
    @test string(Bare(99)) == "099"
    # No parse/tryparse defined
    @test_throws MethodError parse(Bare, "042")
end

# --- Isolation verification ---

@testset "no AbstractIdentifier dependency" begin
    @defpacked IsoCheck (:n(digits(2)))
    @test !(IsoCheck <: FastIdentifiers.AbstractIdentifier)
    @test IsoCheck <: AbstractPacked
end

# --- Round-trip invariant across all test types ---

@testset "round-trip invariant" begin
    samples = [
        LitDigit(0), LitDigit(42), LitDigit(9999),
        parse(Colour, "red"), parse(Colour, "green"), parse(Colour, "blue"),
        Flagged(:alpha, 7), Flagged(:gamma, 999),
        parse(Skipped, "12345"), parse(Skipped, "http://99999"),
        parse(Code3, "ABC"), parse(Code3, "XYZ"),
        parse(AlphaNum4, "AB12"), parse(AlphaNum4, "ZZ99"),
        parse(HexId, "DEAD"), parse(HexId, "00FF"),
        parse(BinId, "10110010"), parse(BinId, "00000000"),
        OptSuffix(42, nothing), OptSuffix(42, 7),
        NestedOpt(42, nothing, nothing), NestedOpt(42, 5, 10),
        Constructed(42, :y), Constructed(0, :z),
        OptCons(5, 3), OptCons(5, nothing),
        parse(Ordered, "0100"), parse(Ordered, "9999"),
    ]
    for x in samples
        T = typeof(x)
        @test parse(T, string(x)) == x
    end
end

end # @testset "PackedParselets"
