# SPDX-FileCopyrightText: © 2025 TEC <contact@tecosaur.net>
# SPDX-License-Identifier: MPL-2.0

# Identifier-specific method assembly: parse/tryparse with MalformedIdentifier
# and ChecksumViolation, shortcode, and purlprefix emission.

"""
    defid_make(exprs, state, name, segments) -> Expr(:toplevel, ...)

Assemble all method definitions for the generated identifier type.

Delegates to `assemble_type` for generic methods, with `identifier_finalize!`
providing identifier-specific parse/tryparse, shortcode, and purlprefix.
"""
function defid_make(exprs::PatternExprs, state::DefIdState, name::Symbol,
                    segments::NamedTuple = (;))
    assemble_type(exprs, state, name, segments;
                  finalize_fn = identifier_finalize!)
end

## Identifier-specific finalization

function identifier_finalize!(block::Expr, exprs::PatternExprs,
                              state::DefIdState, name::Symbol)
    ename = esc(name)
    # parse/tryparse with MalformedIdentifier and ChecksumViolation
    push!(block.args, identifier_parse(state, name)...)
    # Rewrite methods generated by assemble_type for identifier semantics:
    # - Base.print(io, id) → FastIdentifiers.shortcode(io, id)
    #   The generic AbstractIdentifier.print handles PURL prefixing.
    # - Base.show's :limit branch: print(io, id) → shortcode(io, id)
    #   Since print now goes through AbstractIdentifier (PURL-aware).
    shortcode_ref = GlobalRef(FastIdentifiers, :shortcode)
    print_ref = GlobalRef(Base, :print)
    show_ref = GlobalRef(Base, :show)
    for arg in block.args
        arg isa Expr && Meta.isexpr(arg, :function) || continue
        sig = arg.args[1]
        Meta.isexpr(sig, :call) && !isempty(sig.args) || continue
        if sig.args[1] == print_ref
            # Rewrite Base.print → FastIdentifiers.shortcode
            sig.args[1] = shortcode_ref
        elseif sig.args[1] == show_ref
            # In show's :limit branch, rewrite print(io, id) → shortcode(io, id)
            rewrite_show_print_to_shortcode!(arg, shortcode_ref)
        end
    end
    # shortcode(id) -> string(id) for the String form
    push!(block.args,
        :($(shortcode_ref)(id::$ename) = string(id)))
    # purlprefix
    prefix = get(state.globals, :purlprefix, nothing)
    if !isnothing(prefix)
        push!(block.args,
              :($(GlobalRef(FastIdentifiers, :purlprefix))(::Type{$ename}) = $prefix))
    end
end

# In the show method's :limit branch, the generated code calls `print(io, id)`.
# For identifiers, `print` dispatches to the generic AbstractIdentifier method
# which prepends the PURL prefix — wrong for show's compact form. Rewrite
# `print(io, id)` to `shortcode(io, id)` where `id` is the function argument.
function rewrite_show_print_to_shortcode!(expr::Expr, shortcode_ref::GlobalRef)
    for (i, arg) in enumerate(expr.args)
        arg isa Expr || continue
        if Meta.isexpr(arg, :call) && length(arg.args) == 3 &&
           arg.args[1] === :print && arg.args[2] === :io && arg.args[3] === :id
            arg.args[1] = shortcode_ref
        else
            rewrite_show_print_to_shortcode!(arg, shortcode_ref)
        end
    end
end

## parse / tryparse

function identifier_parse(state::DefIdState, name::Symbol)
    errmsgs = Tuple(state.errconsts)
    ename = esc(name)
    checkdigit_output = let idx = findfirst(p -> first(p) === :checkdigit, state.segment_outputs)
        isnothing(idx) ? nothing : last(state.segment_outputs[idx])
    end
    has_checksum = !isnothing(checkdigit_output)
    parse_body = if has_checksum
        info = checkdigit_output.meta.context::ChecksumInfo
        fn_ref = info.fn
        byte_to_val = info.parse_expr
        quote
            result, pos = parsebytes($ename, codeunits(id))
            if result isa $ename
                if pos < 0
                    # Checksum violation: re-read the check byte to report provided value
                    checkbyte = @inbounds codeunits(id)[-pos]
                    provided = $byte_to_val
                    throw(ChecksumViolation{$ename}(id, idchecksum(result), provided))
                end
                pos > ncodeunits(id) || throw(MalformedIdentifier{$ename}(id, "Unparsed trailing content"))
                result
            else
                throw(MalformedIdentifier{$ename}(id, @inbounds $errmsgs[result]))
            end
        end
    else
        quote
            result, pos = parsebytes($ename, codeunits(id))
            if result isa $ename
                pos > ncodeunits(id) || throw(MalformedIdentifier{$ename}(id, "Unparsed trailing content"))
                result
            else
                throw(MalformedIdentifier{$ename}(id, @inbounds $errmsgs[result]))
            end
        end
    end
    tryparse_cond = if has_checksum
        :(result isa $ename && pos > 0 && pos > ncodeunits(id))
    else
        :(result isa $ename && pos > ncodeunits(id))
    end
    (:(function $(GlobalRef(Base, :parse))(::Type{$ename}, id::AbstractString)
           $(parse_body.args...)
       end),
     :(function $(GlobalRef(Base, :tryparse))(::Type{$ename}, id::AbstractString)
           result, pos = parsebytes($ename, codeunits(id))
           if $tryparse_cond
               result
           end
       end))
end

